name: Go Build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build Go Project
    runs-on: [arc-runner]

    env:
      FOO: bar

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3

      - name: Prepare environment
        run: |
          # mkdir -p $GOPATH
          go env

      - name: Build project
        run: |
          mkdir -p output
          go build -o output/foobar main.go

      - name: Sleep for debugging
        # This step is for debugging purposes, it can be removed in production
        run: sleep 1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-build-output
          path: output/
          retention-days: 1
